name: Build and Deploy
on:
  push:
    branches:
      - main
  schedule:
    - cron: "20 2 * * *"
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .

      - name: Copy senior rankings data
        run:
          mkdir data && curl https://wca-seniors.org/data/Senior_Rankings.js > Senior_Rankings.js
