name: Build and Deploy
on:
  push:
    branches:
      - main

  schedule:
    - cron: "20 2 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: Vite Build
        run: npm run build

      - name: Copy senior rankings data
        run: npm run get-data

      - name: Convert data to JSON
        run: num run convert-data

      - name: Create .nojekyll
        run: touch ./dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
